### ISSUE TITLE
Please bypass cache

### ISSUE THREAD

**Issue by morrisjdev** [Techniv/gulp-less-json-import#2]
Can you please Bypass the cache of json files, so that I can use your great tool with gulp and watch?

You simply can change the line:

jsonContent = require(jsonPath);

to

jsonContent = JSON.parse(fs.readFileSync(jsonPath, {encoding: "utf-8", flat: "rs"}));

That works :)

Thanks

**Comment by Techniv** [comment]
I fixed it.
You can update to [1.2.0](https://github.com/Techniv/gulp-less-json-import/blob/v1.2.0/CHANGELOG.md)
